[tool.poetry]
name = "open-offheart"
version = "0.1.0"
description = ""
authors = ["Metropolix"]
readme = "README.md"
packages = [{include = "open_offheart"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
